Make Lab 1
afafos/spbstu_science_of_programming pull request #1
Opened 2023-10-01 18:31 UTC by afafos

2023-10-08 15:52 UTC, Kauter1989 requested changes

2023-10-08 15:52 UTC, Kauter1989 commented on CMakeProject/CMakeLists.txt
> +configure_file(${PROJECT_SOURCE_DIR}/plugins/funcsin.dll ${PROJECT_BINARY_DIR}/plugins/funcsin.dll COPYONLY)
Библиотеки не должны никак подгружаться через cmake, они полностью должны быть найдены на рантайме, причем нет фиксированного списка функциональности - что нашли, то и подгрузили

2023-10-08 15:52 UTC, Kauter1989 commented on CMakeProject/README.md
> +- `funcpower.cpp` - Реализация функции `degree`.
если добавить сюда новый плагин с arctan, например, то понадобится пересборка проекта - а этого не должно быть, все плагины ищутся на рантайме

2023-10-10 12:30 UTC, afafos commented on CMakeProject/CMakeLists.txt
> +configure_file(${PROJECT_SOURCE_DIR}/plugins/funcsin.dll ${PROJECT_BINARY_DIR}/plugins/funcsin.dll COPYONLY)
Исправил, пришлось переделать полностью логику, так как везде в алгоритме использовал знание о том, какие функции подгружаем (первые буквы функций и не только). Теперь символьное обозначение функций я считываю из .dll, что позволяет без пересборки проекта добавлять новые .dll в калькулятор

2023-10-11 17:26 UTC, Kauter1989 requested changes

2023-10-11 17:26 UTC, Kauter1989 commented on CMakeProject1/algorithm.cpp
> +                    if (c == 2) {
Что такое с? Называйте переменные осмысленно, ф-ю надо разбить на большее количество

2023-10-11 17:26 UTC, Kauter1989 commented on CMakeProject1/struct.h
> +    int un_or_bin; // 1 for unary, 2 for binary
тут енам должен быть, а не инт, который не передает ничего, и означает кратно больший диапазон значений

2023-10-11 17:26 UTC, Kauter1989 commented on CMakeProject1/algorithm.cpp
> +                double r = res_stack.back();
различные кейсы, по сути, означают различные ф-и. int в условии прячет эту семантику и ухудшает читаемость

2023-10-11 19:29 UTC, afafos commented on CMakeProject1/algorithm.cpp
> +                    if (c == 2) {
Исправил: постарался назвать более осмысленно

2023-10-11 19:30 UTC, afafos commented on CMakeProject1/struct.h
> +    int un_or_bin; // 1 for unary, 2 for binary
Исправил: сделал через enum class

2023-10-11 19:30 UTC, afafos commented on CMakeProject1/algorithm.cpp
> +                double r = res_stack.back();
Исправил: через enum class стало более читаемо

2023-10-12 18:16 UTC, Kauter1989 requested changes

2023-10-12 18:16 UTC, Kauter1989 commented on CMakeProject1/algorithm.cpp
> +                if (sc == "(") {
Почему здесь строковая константа, а 10 строчками выше - точно такое же сравнение, но символьное? либо вы не выделили в класс операторы скобок, либо хранение единичных символов в виде строк(контейнеров) как операторов - избыточно

2023-10-12 18:16 UTC, Kauter1989 commented on CMakeProject1/algorithm.cpp
> +            while (i < expression.length()) {
логика алгоритма выполнена единым нечитаемым полотном, переменные названы неинформативно

2023-10-12 18:16 UTC, Kauter1989 commented on CMakeProject1/algorithm.cpp
> +    for (const auto& token : tokens) {
Этот код вообще не связан с предыдущим, и опять осуществляет одновременно и символьный, и стековый разбор

2023-10-12 18:16 UTC, Kauter1989 commented on CMakeProject1/algorithm.cpp
> +        return 10; // All binary operators have the same precedence
что такое 10?

2023-10-12 18:16 UTC, Kauter1989 commented on CMakeProject1/algorithm.cpp
> +        return 10;
if не имеет смысла

2023-10-12 18:16 UTC, Kauter1989 commented on CMakeProject1/funccos.cpp
> +    __declspec(dllexport) const char* get_sym() {
у вас одновременно есть и данные, и методы, но вы все экспортируете в С стиле, а мы изучаем другой язык программирования

2023-10-12 19:14 UTC, afafos commented on CMakeProject1/algorithm.cpp
> +                if (sc == "(") {
Здесь char сравнивается с char, а строка со строкой. Cкобки не выделены в операторы, потому что это такие технические символы в выражении, которые обрабатываются особенно: потому что это не бинарная, не унарная, вообще ни какая не операция. То, что в скобках, просто подвыражение или подформула. Для скобок не нужен отдельный контейнер

2023-10-13 09:58 UTC, afafos commented on CMakeProject1/algorithm.cpp
> +        return 10; // All binary operators have the same precedence
Исправил: если оператор бинарный, то возвращаем приоритет этого оператора, иначе - возвращаем значение 10. Так устанавливаю приоритет для операторов в выражении

2023-10-13 09:58 UTC, afafos commented on CMakeProject1/algorithm.cpp
> +        return 10;
Исправил: см. коммент выше

2023-10-13 10:00 UTC, afafos commented on CMakeProject1/algorithm.cpp
> +            while (i < expression.length()) {
Исправил: разбил функцию parse_expression ещё на 2 функции (get_tokens и perform_tokens). Добавил ещё комментариев

2023-10-13 10:00 UTC, afafos commented on CMakeProject1/algorithm.cpp
> +    for (const auto& token : tokens) {
Разбил на функции, всё связано

2023-10-13 17:42 UTC, afafos commented on CMakeProject1/funccos.cpp
> +    __declspec(dllexport) const char* get_sym() {
Исправил: обернул в классы

2023-10-22 11:06 UTC, merged